Added init and quit submodule to wrapper
MasterQ32/SDL.zig pull request #74
Opened 2022-06-26 20:55 UTC by Sucuturdean

2022-06-27 08:15 UTC, MasterQ32 requested changes

2022-06-27 08:15 UTC, MasterQ32 commented on src/wrapper/sdl.zig
> +pub const initSubmodule = init;
[`SDL_InitSubSystem`](https://wiki.libsdl.org/SDL_InitSubSystem) is not `SDL_Init`, even if they are defined identical in SDL2. Please use `SDL_InitSubSystem` here.

Also please call the function alias `initSubSystem`

2022-06-27 08:15 UTC, MasterQ32 commented on src/wrapper/sdl.zig
> +pub fn quitSubsystem(flags: InitFlags) void {
Please rename this into `quitSubSystem`

2022-06-28 08:25 UTC, Sucuturdean commented
Added and modified everything you asked.

2022-06-28 10:24 UTC, merged